plugins: rubocop-rspec

AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  NewCops: enable
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/StringLiterals:
  Exclude:
    - 'db/migrate/*'